# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dab673e7d6aa5f4e901b655f8e918c4170975f2f1c3aab833f0835ba5ab505ece1390253599747ee91eaebdf522f5c3d6e4500040e8c9dd3c7d38725bb82a73

test:
  secret_key_base: 914e1829c8e5400892c15e994f3ec8ee66153d65365cde6213f32283b7dadaf0887d8a5e37a6625eb4b402eb690fbad54b86f73e23d6161e97423a651f5350aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
